version: "3.9"

services:
  db:
    image: mysql:latest
  web:
    build: .
    command: python manage.py runserver localhost:8000
    ports:
      - "8000:8000"
    environment:
        MYSQL_DATABASE: recruitmentTest
        MYSQL_USER: root
        MYSQL_PASSWORD:
    depends_on:
      - db